### ISSUE TITLE
Bug report #1

### ISSUE THREAD

**Issue by biunang** [ziap/infinite-minesweeper#3] opened 2022-02-09 04:57 UTC
bugs:
- lose focus when moving cursor out of the game, causing it to get stuck at dragging mode
- not able to differentiate between flag mode on pc until the cursor is away
- abnormal zoom scaling on pc

possible fixes:
- remove dragging state once out of focus
- revert back to the original state when hover on the activated state
- reduce scaling by approximately 5 times

**Comment by ziap** [comment] 2022-02-09 04:59
1. is duplicate of #1

**Comment by ziap** [comment] 2022-02-09 06:21
Current solution
- [x] Remove dragging state once out of focus
- [x] Use different hover color to differentiate
- [x] Fixed the scaling and also make it scale to cursor

**Closed as completed** 2022-02-09 07:04 UTC
Labels: bug, good first issue
